CREATE DATABASE IF NOT EXISTS student;
USE student;

DROP TABLE IF EXISTS STUDENT;

CREATE TABLE STUDENT (
    NAME VARCHAR(25),
    CLASS VARCHAR(25),
    SECTION VARCHAR(25),
    MARKS INT
);

INSERT INTO STUDENT VALUES ('Aastha', 'Data Science', 'A', 90);
INSERT INTO STUDENT VALUES ('John', 'Data Science', 'B', 100);
INSERT INTO STUDENT VALUES ('Mukesh', 'Data Science', 'A', 86);
SELECT * FROM STUDENT;
